namespace FIInstrumentation.Types;

public enum EvalName
{
    ConversationCoherence,
    ConversationResolution,
    ContentModeration,
    ContextAdherence,
    ContextRelevance,
    Completeness,
    ChunkAttribution,
    ChunkUtilization,
    Pii,
    Toxicity,
    Tone,
    Sexist,
    PromptInjection,
    PromptInstructionAdherence,
    DataPrivacyCompliance,
    IsJson,
    OneLine,
    ContainsValidLink,
    IsEmail,
    NoValidLinks,
    Groundedness,
    EvalRanking,
    SummaryQuality,
    FactualAccuracy,
    TranslationAccuracy,
    CulturalSensitivity,
    BiasDetection,
    AudioTranscription,
    AudioQuality,
    NoRacialBias,
    NoGenderBias,
    NoAgeBias,
    NoOpenaiReference,
    NoApologies,
    IsPolite,
    IsConcise,
    IsHelpful,
    IsCode,
    FuzzyMatch,
    AnswerRefusal,
    DetectHallucination,
    NoHarmfulTherapeuticGuidance,
    ClinicallyInappropriateTone,
    IsHarmfulAdvice,
    ContentSafetyViolation,
    IsGoodSummary,
    IsFactuallyConsistent,
    IsCompliant,
    IsInformalTone,
    EvaluateFunctionCalling,
    TaskCompletion,
    CaptionHallucination,
    BleuScore,
    RougeScore,
    TextToSql,
    RecallScore,
    LevenshteinSimilarity,
    NumericSimilarity,
    EmbeddingSimilarity,
    SemanticListContains,
    IsAiGeneratedImage,
}

public static class EvalNameExtensions
{
    public static string ToValue(this EvalName name) => name switch
    {
        EvalName.ConversationCoherence => "conversation_coherence",
        EvalName.ConversationResolution => "conversation_resolution",
        EvalName.ContentModeration => "content_moderation",
        EvalName.ContextAdherence => "context_adherence",
        EvalName.ContextRelevance => "context_relevance",
        EvalName.Completeness => "completeness",
        EvalName.ChunkAttribution => "chunk_attribution",
        EvalName.ChunkUtilization => "chunk_utilization",
        EvalName.Pii => "pii",
        EvalName.Toxicity => "toxicity",
        EvalName.Tone => "tone",
        EvalName.Sexist => "sexist",
        EvalName.PromptInjection => "prompt_injection",
        EvalName.PromptInstructionAdherence => "prompt_instruction_adherence",
        EvalName.DataPrivacyCompliance => "data_privacy_compliance",
        EvalName.IsJson => "is_json",
        EvalName.OneLine => "one_line",
        EvalName.ContainsValidLink => "contains_valid_link",
        EvalName.IsEmail => "is_email",
        EvalName.NoValidLinks => "no_valid_links",
        EvalName.Groundedness => "groundedness",
        EvalName.EvalRanking => "eval_ranking",
        EvalName.SummaryQuality => "summary_quality",
        EvalName.FactualAccuracy => "factual_accuracy",
        EvalName.TranslationAccuracy => "translation_accuracy",
        EvalName.CulturalSensitivity => "cultural_sensitivity",
        EvalName.BiasDetection => "bias_detection",
        EvalName.AudioTranscription => "audio_transcription",
        EvalName.AudioQuality => "audio_quality",
        EvalName.NoRacialBias => "no_racial_bias",
        EvalName.NoGenderBias => "no_gender_bias",
        EvalName.NoAgeBias => "no_age_bias",
        EvalName.NoOpenaiReference => "no_openai_reference",
        EvalName.NoApologies => "no_apologies",
        EvalName.IsPolite => "is_polite",
        EvalName.IsConcise => "is_concise",
        EvalName.IsHelpful => "is_helpful",
        EvalName.IsCode => "is_code",
        EvalName.FuzzyMatch => "fuzzy_match",
        EvalName.AnswerRefusal => "answer_refusal",
        EvalName.DetectHallucination => "detect_hallucination",
        EvalName.NoHarmfulTherapeuticGuidance => "no_harmful_therapeutic_guidance",
        EvalName.ClinicallyInappropriateTone => "clinically_inappropriate_tone",
        EvalName.IsHarmfulAdvice => "is_harmful_advice",
        EvalName.ContentSafetyViolation => "content_safety_violation",
        EvalName.IsGoodSummary => "is_good_summary",
        EvalName.IsFactuallyConsistent => "is_factually_consistent",
        EvalName.IsCompliant => "is_compliant",
        EvalName.IsInformalTone => "is_informal_tone",
        EvalName.EvaluateFunctionCalling => "evaluate_function_calling",
        EvalName.TaskCompletion => "task_completion",
        EvalName.CaptionHallucination => "caption_hallucination",
        EvalName.BleuScore => "bleu_score",
        EvalName.RougeScore => "rouge_score",
        EvalName.TextToSql => "text_to_sql",
        EvalName.RecallScore => "recall_score",
        EvalName.LevenshteinSimilarity => "levenshtein_similarity",
        EvalName.NumericSimilarity => "numeric_similarity",
        EvalName.EmbeddingSimilarity => "embedding_similarity",
        EvalName.SemanticListContains => "semantic_list_contains",
        EvalName.IsAiGeneratedImage => "is_AI_generated_image",
        _ => throw new ArgumentOutOfRangeException(nameof(name)),
    };
}
